export const adminLinks = [
  { to: '/admin', label: 'Ringkasan' },
  { to: '/admin/profil', label: 'Profil & Kontak' },
  { to: '/admin/tenaga-pendidik', label: 'Tenaga Pendidik' },
  { to: '/admin/fasilitas', label: 'Fasilitas' },
  { to: '/admin/kemitraan', label: 'Kemitraan Sekolah' },
  { to: '/admin/tampilan', label: 'Pengaturan Tampilan' },
  { to: '/admin/pengumuman', label: 'Pengumuman' },
  { to: '/admin/berita', label: 'Berita' },
  { to: '/admin/agenda', label: 'Agenda Kegiatan' },
  { to: '/admin/galeri', label: 'Galeri Foto' },
  { to: '/admin/pembelajaran', label: 'Pembelajaran' },
  { to: '/admin/materi', label: 'Semua Materi' },
  { to: '/admin/aplikasi', label: 'Aplikasi Sekolah' },
  { to: '/admin/pengguna', label: 'Kelola Guru' },
]
